name: Manual Build

#on: push
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    env:
      ARCH: amd64
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_OPTIONS: -A x64 -DDEPRECATE_HARD=ON -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CLI=ON -DCMAKE_BUILD_TYPE=Release
      CMAKE_BUILD_OPTIONS: --config Release
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: source
        fetch-depth: 1
    - name: Build
      shell: bash
      run: |
        pwd
        ls -al
        cd source
        pwd
        ls -al
        cmake -A x64 -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64.dll" .
        cmake --build . --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dlls
        path: |
          build/Release/libgit2-x64.dll
