name: Windows DLLs

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with: 
        fetch-depth: 1
    - name: Build
      shell: bash
      run: |
        cmake -A x64 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64" .
        cmake --build . --config Release
        cmake -A x64 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64-dbg" .
        cmake --build . --config Debug
        rm -rf CMakeCache.txt CMakeFiles
        cmake -A Win32 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86" .
        cmake --build . --config Release
        cmake -A Win32 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86-dbg" .
        cmake --build . --config Debug
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dlls
        path: |
          Release/libgit2-x64.dll
          Debug/libgit2-x64-dbg.dll
          Debug/libgit2-x64-dbg.pdb
          Release/libgit2-x86.dll
          Debug/libgit2-x86-dbg.dll
          Debug/libgit2-x86-dbg.pdb

#        path: x64

#        rm -rf x64/tests #remove tests directory which contains symbolic link that can't be copied with cp
#        cp -r x64 x86
#        cd x64
#        cmake -A x64 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64" .
#        cmake --build . --config Release
#        cmake -A x64 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64-dbg" .
#        cmake --build . --config Debug
#        cd ../x86
#        cmake -A x86 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86" .
#        cmake --build . --config Release
#        cmake -A x86 -D DEPRECATE_HARD=ON -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86-dbg" .
#        cmake --build . --config Debug

#        rm -rf CMakeCache.txt CMakeFiles
#        mv Debug ..
#        pwd
#        ls -al ../Debug
#on: 
#        cd source
#        cmake -A x86 -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86-dbg" .
#        cmake --build . --config Debug
#          Release/libgit2-x86-dbg.dll
#          Release/libgit2-x86-dbg.pdb
