name: Manual Build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: source
        fetch-depth: 0
    - name: Build
      shell: bash
      run: |
#        cd source
        cmake -A x64 -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64-dbg" .
        cmake --build . --config Debug
#        cmake -A x86 -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86-dbg" .
#        cmake --build . --config Debug
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dlls
        path: |
          Debug/libgit2-x64-dbg.dll
          Debug/libgit2-x64-dbg.pdb
#          Release/libgit2-x86-dbg.dll
#          Release/libgit2-x86-dbg.pdb
