name: Manual Build

#on: push
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: source
        fetch-depth: 1
    - name: Build
      shell: bash
      run: |
        cd source
        cmake -A x64 -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x64" .
        cmake --build . --config Release
#        cmake -A x86 -D USE_SSH=OFF -D USE_HTTPS=WinHTTP -D "BUILD_TESTS=OFF" -D "BUILD_CLI=OFF" -D "LIBGIT2_FILENAME=libgit2-x86" .
#        cmake --build . --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dlls
        path: |
          build/Release/libgit2-x64.dll
#          build/Release/libgit2-x86.dll
