name: Push Build

on: [push]

jobs:
  build:
    runs-on: windows-2019
    env:
      ARCH: amd64
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_OPTIONS: -A x64 -DDEPRECATE_HARD=ON -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CLI=ON -DCMAKE_BUILD_TYPE=Release
      CMAKE_BUILD_OPTIONS: --config Release
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: source
        fetch-depth: 0
    - name: Build
      shell: bash
      run: |
        source/ci/setup-win32-build.sh
        mkdir build && cd build
        ../source/ci/build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: exe
        path: build/git2.exe
